const songs = {
  1:"Six Feet Under",
  2:"Sex and the City",
  3:"Ally McBeal",
  4:"Will & Grace",
  5:"Everybody Loves Raymond",
  6:"Frasier",
  7:"Friends",
  8:"Late Show With David Letterman",
  9:"Mad About You",
  10:"Melrose Place",
  11:"Beverly Hills 90210",
  12:"Law & Order",
  13:"Northern Exposure",
  14:"The Simpsons",
  15:"Thirtysomething",
  16:"Full House",
  17:"21 Jump Street",
  18:"L.A. Law",
  19:"Pee-Wee's Playhouse",
  20:"Perfect Strangers",
  21:"Growing Pains",
  22:"Moonlighting",
  23:"Who's The Boss?",
  24:"Miami Vice",
  25:"Night Court",
  26:"The A-Team",
  27:"St. Elsewhere",
  28:"Cheers",
  29:"Knight Rider",
  30:"Cagney & Lacey",
  31:"The Greatest American Hero",
  32:"Hill Street Blues",
  33:"Dynasty",
  34:"Magnum, P.I.",
  35:"The Facts of Life",
  36:"Diff'rent Strokes",
  37:"WKRP In Cincinnati",
  38:"Taxi",
  39:"Dallas",
  40:"Fantasy Island",
  41:"The Love Boat",
  42:"Soap",
  43:"Eight Is Enough",
  44:"Three's Company",
  45:"Wonder Woman",
  46:"Charlie's Angels",
  47:"The Muppet Show",
  48:"Alice",
  49:"What's Happening!!",
  50:"Laverne & Shirley",
  51:"One Day At A Time",
  52:"Welcome Back, Kotter",
  53:"Barney Miller",
  54:"Starsky And Hutch",
  55:"S.W.A.T.",
  56:"The Jeffersons",
  57:"Police Woman",
  58:"The Rockford Files",
  59:"Good Times",
  60:"The Six Million Dollar Man",
  61:"M*A*S*H",
  62:"The Waltons",
  63:"Maude",
  64:"Sanford And Son",
  65:"The Odd Couple",
  66:"The Mary Tyler Moore Show",
  67:"Happy Days",
  68:"Sesame Street",
  69:"Love, American Style",
  70:"The Courtship Of Eddie's Father",
  71:"The Brady Bunch",
  72:"Scooby-Doo",
  73:"Hawaii Five-O",
  74:"The Banana Splits",
  75:"The Newlywed Game",
  76:"The Dating Game",
  77:"The Monkees",
  78:"Batman",
  79:"I Dream Of Jeannie",
  80:"The Wild Wild West",
  81:"Green Acres",
  82:"Gilligan's Island",
  83:"The Addams Family",
  84:"Bewitched",
  85:"The Jetsons",
  86:"The Dick Van Dyke Show",
  87:"The Andy Griffith Show",
  88:"The Flintstones",
  89:"My Three Sons",
  90:"The Twilight Zone",
  91:"Leave It To Beaver",
  92:"Perry Mason",
  93:"The Honeymooners",
  94:"Merrie Melodies",
  95:"Looney Toons",
  96:"Dragnet",
  97:"I Love Lucy",
  98:"The Lone Ranger",
  99:"Adventure Time",
  100:"Stranger Things",
  101:"Kim Possible",
  102:"Community",
  103:"The Big Bang Theory",
  104:"New Girl",
  105:"Curb Your Enthusiasm",
  106:"Gilmore Girls",
  107:"Game of Thrones",
  108:"Malcolm in the Middle",
  109:"House",
  110:"LAW & ORDER",
  111:"The magic school bus",
  112:"Total drama island"
  }

  export default songs